### ISSUE TITLE
The system cannot find the file specified

### ISSUE THREAD

**Issue by atomikigai** [ONdraid/reve#2]
I follow the steps in your MD but the program exit with panic
![image](https://user-images.githubusercontent.com/30026273/196002707-75420a72-63a6-4a0e-9dcc-75c6b0f01f09.png)
![image](https://user-images.githubusercontent.com/30026273/196002744-154d4329-b935-4f09-acc0-8be33acc7a94.png)

**Comment by ONdraid** [comment]
I know about this issue. The current release lacks post-completion and verification checks. I'll push these in a few days :)

**Comment by ONdraid** [comment]
@ichiroDaiki
ok, I have made a [new release](https://github.com/ONdraid/reve/releases/tag/v0.0.2). please check it out and let me know if the issue still remains.
